# Generated by Django 3.0.2 on 2020-02-26 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Available_Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BookName', models.CharField(max_length=35)),
                ('Ownername', models.CharField(default='', max_length=35)),
                ('Edition', models.IntegerField()),
                ('AuthorName', models.CharField(max_length=25)),
                ('Publication', models.CharField(max_length=25)),
                ('BookCategory', models.CharField(max_length=25)),
                ('img', models.ImageField(upload_to='pics')),
                ('pdf', models.FileField(upload_to='pdf')),
                ('Department', models.CharField(max_length=25)),
                ('Semester', models.IntegerField()),
                ('Return', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Available_Stationary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stationary_Name', models.CharField(max_length=35)),
                ('img', models.ImageField(upload_to='SImage')),
                ('Stationary_Description', models.CharField(max_length=1000)),
            ],
        ),
    ]
