# Generated by Django 3.0.2 on 2020-02-26 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BSS', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='available_books',
            name='Return',
        ),
    ]
