# Generated by Django 3.0.2 on 2020-02-28 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BSS', '0004_total_books'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sent_Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Message', models.CharField(max_length=1000)),
            ],
        ),
    ]
